# Teste da rota GET /users
POST http://localhost:3000/api/users
Content-Type: : application/json

{
    "full_name": "Tobias Viana",
    "username": "TobiTeste",
    "email" : "tobi@gmail.com"
}


GET http://localhost:3000/api/users
Accept: application/json